spring.application.name=demo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}

# =================================================================================================
# WARNING: Do not store secrets like database passwords directly in this file in a real application.
# This is a temporary solution to get the application running.
# In a production environment, use environment variables or a secret management tool.
# =================================================================================================

spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
